on:
  push

jobs:
  export_game:
    name: Export game
    runs-on: ubuntu-latest
    outputs:
      build_directory: ${{ steps.export.outputs.build_directory }}
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
      with:
        lfs: true
    - name: dotnet build
      run: dotnet build
    - name: export game
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/mono/Godot_v4.1.1-stable_mono_linux_x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/mono/Godot_v4.1.1-stable_mono_export_templates.tpz
        relative_project_path: ./
        cache: true
    # - name: upload windows artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: windows_build
    #     path: ${{ steps.export.outputs.build_directory }}/Windows Desktop
    - name: upload linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux_build
        path: ${{ steps.export.outputs.build_directory }}/LinuxX11
  upload_to_itch:
    name: Upload linux build to itch.io
    runs-on: ubuntu-latest
    needs: export_game
    steps:
    - name: download linux build
      uses: actions/download-artifact@v3
      with:
        name: linux_build
    - name: check contents
      run: ls -R
    - name: upload linux build
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: buildsystemtestprivate
        ITCH_USER: redglow
        PACKAGE: ./linux_build