on:
  push

jobs:
  export_game:
    name: Export game
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - name: dotnet build
      run: dotnet build
    - name: export game
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/mono/Godot_v4.1.1-stable_mono_linux_x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/mono/Godot_v4.1.1-stable_mono_export_templates.tpz
        relative_project_path: ./
        archive_output: true