on:
  # push
  issues:
    types:
      - opened

jobs:
  export_game_dev:
    uses: ./.github/workflows/export_game.yml
    with:
      project_name: buildsystemtestprivate
    secrets:
      BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}