on:
  push

jobs:
  export_game_dev:
    uses: ./.github/workflows/export_game.yml
    with:
      project_name: ${{ vars.PRIVATE_PROJECT_NAME }}
    secrets:
      BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}