on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      project_name:
        required: true
        type: string
    secrets:
      BUTLER_CREDENTIALS:
        required: true

jobs:
  export_game:
    name: Export game
    runs-on: ubuntu-latest
    outputs:
      build_directory: ${{ steps.export.outputs.build_directory }}
    steps:
    - name: print
      run: |
        echo project_name = "${{ inputs.project_name }}""
        echo version = "${{ inputs.version }}""
    - name: checkout
      uses: actions/checkout@v3.3.0
      with:
        lfs: true
    - name: dotnet build
      run: dotnet build
    - name: export game
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/mono/Godot_v4.1.1-stable_mono_linux_x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/mono/Godot_v4.1.1-stable_mono_export_templates.tpz
        relative_project_path: ./
        cache: true
    - name: upload windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows_build
        path: ${{ steps.export.outputs.build_directory }}/Windows Desktop
    - name: upload linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux_build
        path: ${{ steps.export.outputs.build_directory }}/LinuxX11
  upload_to_itch_linux:
    name: Upload linux build to itch.io
    runs-on: ubuntu-latest
    needs: export_game
    steps:
    - name: download linux build
      uses: actions/download-artifact@v3
      with:
        name: linux_build
        path: ./linux_build
    - name: upload linux build
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: ${{ inputs.project_name }}
        ITCH_USER: ${{ vars.ITCH_USER }}
        PACKAGE: ./linux_build
        VERSION: ${{ inputs.version }}
  upload_to_itch_windows:
    name: Upload windows build to itch.io
    runs-on: ubuntu-latest
    needs: export_game
    steps:
    - name: print
      run: |
        echo "project name = ${{ inputs.project_name }}; version = ${{ inputs.version }}"
    - name: download windows build
      uses: actions/download-artifact@v3
      with:
        name: windows_build
        path: ./windows_build
    - name: upload windows build
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: ${{ inputs.project_name }}
        ITCH_USER: ${{ vars.ITCH_USER }}
        PACKAGE: ./windows_build
        VERSION: ${{ inputs.version }}